-- Create Countries Table
CREATE TABLE IF NOT EXISTS countries (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  flag TEXT NOT NULL,
  associate BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for countries
ALTER TABLE countries ENABLE ROW LEVEL SECURITY;

-- Create Policy for countries (Allow Read Access to Everyone)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'countries' AND policyname = 'Enable read access for all users'
    ) THEN
        CREATE POLICY "Enable read access for all users" ON countries FOR SELECT USING (true);
    END IF;
END
$$;

-- Seed Countries Data
INSERT INTO countries (code, name, flag, associate) VALUES
('AG', 'Antigua and Barbuda', '🇦🇬', false),
('BS', 'The Bahamas', '🇧🇸', false),
('BB', 'Barbados', '🇧🇧', false),
('BZ', 'Belize', '🇧🇿', false),
('DM', 'Dominica', '🇩🇲', false),
('GD', 'Grenada', '🇬🇩', false),
('GY', 'Guyana', '🇬🇾', false),
('HT', 'Haiti', '🇭🇹', false),
('JM', 'Jamaica', '🇯🇲', false),
('MS', 'Montserrat', '🇲🇸', false),
('KN', 'St. Kitts and Nevis', '🇰🇳', false),
('LC', 'St. Lucia', '🇱🇨', false),
('VC', 'St. Vincent and the Grenadines', '🇻🇨', false),
('SR', 'Suriname', '🇸🇷', false),
('TT', 'Trinidad and Tobago', '🇹🇹', false),
('AI', 'Anguilla', '🇦🇮', true),
('BM', 'Bermuda', '🇧🇲', true),
('VG', 'British Virgin Islands', '🇻🇬', true),
('KY', 'Cayman Islands', '🇰🇾', true),
('TC', 'Turks and Caicos Islands', '🇹🇨', true)
ON CONFLICT (code) DO NOTHING;

-- Create Businesses Table
CREATE TABLE IF NOT EXISTS businesses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  industry TEXT NOT NULL,
  country_code TEXT REFERENCES countries(code),
  description TEXT,
  address TEXT,
  logo_url TEXT,
  services TEXT[],
  voice_chat_embed TEXT,
  text_chat_embed TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for businesses
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;

-- Create Policy for businesses (Allow Read Access to Everyone)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'businesses' AND policyname = 'Enable read access for all users'
    ) THEN
        CREATE POLICY "Enable read access for all users" ON businesses FOR SELECT USING (true);
    END IF;
END
$$;

-- Seed Businesses Data
INSERT INTO businesses (name, industry, country_code, description, address, logo_url, services, voice_chat_embed, text_chat_embed) VALUES
('Island Grill & Bar', 'restaurant', 'BB', 'Authentic Caribbean cuisine with oceanfront dining. Specializing in fresh seafood and local delicacies.', 'Bay Street, Bridgetown', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=100&h=100&fit=crop', ARRAY['Dine-in', 'Takeaway', 'Catering', 'Private Events'], 'demo-voice-1', 'demo-text-1'),
('Caribbean Legal Associates', 'professional', 'BB', 'Full-service law firm specializing in corporate law, real estate, and immigration services.', 'Broad Street, Bridgetown', 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=100&h=100&fit=crop', ARRAY['Corporate Law', 'Real Estate', 'Immigration', 'Litigation'], 'demo-voice-2', 'demo-text-2'),
('AutoCare Plus', 'automotive', 'BB', 'Complete automotive services including repairs, maintenance, and detailing.', 'Warrens, St. Michael', 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=100&h=100&fit=crop', ARRAY['Repairs', 'Oil Change', 'Detailing', 'Tire Services'], 'demo-voice-3', 'demo-text-3'),
('Wellness Medical Center', 'healthcare', 'BB', 'Comprehensive healthcare services with modern facilities and experienced professionals.', 'Hastings, Christ Church', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=100&h=100&fit=crop', ARRAY['General Practice', 'Specialist Care', 'Lab Services', 'Pharmacy'], 'demo-voice-4', 'demo-text-4'),
('Tropic Realty', 'realestate', 'BB', 'Premier real estate agency offering residential and commercial properties across the island.', 'Holetown, St. James', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=100&h=100&fit=crop', ARRAY['Sales', 'Rentals', 'Property Management', 'Valuations'], 'demo-voice-5', 'demo-text-5'),
('Jerk Pit Kingston', 'restaurant', 'JM', 'Authentic Jamaican jerk cuisine, famous for our secret family recipe.', 'Hope Road, Kingston', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=100&h=100&fit=crop', ARRAY['Dine-in', 'Delivery', 'Catering'], 'demo-voice-6', 'demo-text-6'),
('Port of Spain Motors', 'automotive', 'TT', 'Authorized dealer for major automotive brands with full service center.', 'Wrightson Road, Port of Spain', 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=100&h=100&fit=crop', ARRAY['New Cars', 'Used Cars', 'Financing', 'Service Center'], 'demo-voice-7', 'demo-text-7'),
('Nassau Paradise Tours', 'tourism', 'BS', 'Explore the beauty of The Bahamas with our exclusive tour packages.', 'Bay Street, Nassau', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=100&h=100&fit=crop', ARRAY['Island Tours', 'Boat Excursions', 'Snorkeling', 'Private Charters'], 'demo-voice-8', 'demo-text-8'),
('Georgetown Construction Co.', 'construction', 'GY', 'Leading construction company specializing in residential and commercial projects.', 'Main Street, Georgetown', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=100&h=100&fit=crop', ARRAY['Construction', 'Renovation', 'Project Management', 'Consulting'], 'demo-voice-9', 'demo-text-9'),
('St. Lucia Learning Academy', 'education', 'LC', 'Quality education and professional development courses for all ages.', 'Castries, St. Lucia', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=100&h=100&fit=crop', ARRAY['Tutoring', 'Test Prep', 'Professional Courses', 'Online Learning'], 'demo-voice-10', 'demo-text-10');
