-- Create Quote Parameters Table (Form Definitions)
CREATE TABLE IF NOT EXISTS quote_parameters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  field_type TEXT NOT NULL CHECK (field_type IN ('text', 'number', 'select', 'textarea', 'checkbox')),
  options TEXT[], -- Array of strings for Select fields
  is_required BOOLEAN DEFAULT false,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Quotes Table (Submissions)
CREATE TABLE IF NOT EXISTS quotes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id BIGINT REFERENCES businesses(id) ON DELETE CASCADE,
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  form_data JSONB, -- Stores the answers { "Label": "Value" }
  status TEXT DEFAULT 'new', -- new, read, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE quote_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

-- Policies for Quote Parameters
-- 1. Everyone can read parameters (needed for public form)
CREATE POLICY "Public read parameters" ON quote_parameters FOR SELECT USING (true);

-- 2. Business Owners can manage their own parameters
CREATE POLICY "Owners manage parameters" ON quote_parameters
  FOR ALL USING (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.business_id = quote_parameters.business_id
    )
  );

-- Policies for Quotes
-- 1. Public can insert quotes (Submission)
CREATE POLICY "Public submit quotes" ON quotes FOR INSERT WITH CHECK (true);

-- 2. Business Owners can read their own quotes
CREATE POLICY "Owners read quotes" ON quotes
  FOR SELECT USING (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.business_id = quotes.business_id
    )
  );
